### ISSUE TITLE
compléter export sage 

### ISSUE THREAD

**Issue by 926** [weebi-com/yobi_release#30]
- [x] ferme
- [x] avances
- [x] compensation
- [x] salaires
	- .tsv wizall
	- .tsv banque _@MARIKSDE  on a besoin du code comptable ou d'un modèle_

**Comment by MARIKSDE** [comment]
Bonjour Pierre,

Ci-joint le modelé de saisie pour la paie en banque.

*	Code journal :CNCAS
*	N°COMPTE DE LA BANQUE :52120000
*	Même N° de pièce car c’est une seule opération

 

Cdt 

 

 

 

De : Pierre <notifications@github.com> 
Envoyé : lundi 22 juin 2020 09:45
À : weebi-com/yobi_release <yobi_release@noreply.github.com>
Cc : MARIKSDE <mari.faye@ldb.sn>; Mention <mention@noreply.github.com>
Objet : [weebi-com/yobi_release] compléter export sage (#30)

 

*	[X] ferme
*	[X] avances
*	[X] compensation
*	[X] salaires 

*	.tsv wizall
*	.tsv banque @MARIKSDE <https://github.com/MARIKSDE>  on a besoin du code comptable ou d'un modèle

**Comment by 926** [comment]
Merci, ça progresse sur avance et mini-fermes.
Une question pour la compensation, je ne comprends pas pourquoi les versement sur compte client ne sont pas inclus ? Après réflexion il me semble qu'ils sont indépendants des achats. 

Exemple improbable : 
Je dépose 20k sur mon compte au début du mois. J'achète juste pour 15k. Pas de collecte.
A la fin du mois est-ce que ma "compensation" ne devrait pas inclure les 5K ?

**Comment by 926** [comment]
pour finaliser salaires banque il faut en fait d'abord implémenter : https://github.com/weebi-com/yobi_release/issues/32

**Comment by MARIKSDE** [comment]
> 
> 
> Merci, ça progresse sur avance et mini-fermes.
> Une question pour la compensation, je ne comprends pas pourquoi les versement sur compte client ne sont pas inclus ? Après réflexion il me semble qu'ils sont indépendants des achats.
> 
> Exemple improbable :
> Je dépose 20k sur mon compte au début du mois. J'achète juste pour 15k. Pas de collecte.
> A la fin du mois est-ce que ma "compensation" ne devrait pas inclure les 5K ?

Bonjour Pierre, 
desolé pour ce retard
la compense concerne uniquement les éleveur qui donne du lait,
ce qui ne livre pas il achète cash et ne font pas de dépôt 

merci

**Comment by 926** [comment]
Bonjour Mari,
Les premiers exports sont disponibles dans la version 0.5.2.

Désolé, mais je bute toujours sur compensation.
Si je prends un exemple plus réaliste,
J'ai besoin de faire un versement pour acheter des aliments au début du mois. +3K
Je fais mes collectes, avec des volumes record, j'achete un peu d'aliments a credit. +120k - 100k
A la fin du mois, droit d'achat = mon compte le lait (20k) + versements du debut du mois (3K).
=> 23k
Or si on ne compte pas les versements, je n'ai que 20k non ?

**Comment by MARIKSDE** [comment]
Bonsoir Pierre,

sur  ton exemple a la fin du mois le solde de l’éleveur sera de 23k

et ici le montant de la compense c’est 97k ( 100k-3k)

 

le 05/06/20 l’éleveur F a dans son 7k et veut acheter un sac qui coute 10k alors il fait un versement de 3k

donc a la fin du mois son achat de 100k est réglé par :

*	3k de versement client qu’on verra dans la caisse (journal caisse)
*	97k de son compte lait qui correspond au montant à compenser

Son droit d’achat est 23k et son solde compte lait.

 

On peut faire encore un point la dessus au besoin mardi dans l’après - midi.

 

Cordialement 

 

 

 

 

De : Pierre <notifications@github.com> 
Envoyé : vendredi 26 juin 2020 16:14
À : weebi-com/yobi_release <yobi_release@noreply.github.com>
Cc : MARIKSDE <mari.faye@ldb.sn>; Mention <mention@noreply.github.com>
Objet : Re: [weebi-com/yobi_release] compléter export sage (#30)

 

Bonjour Mari,
Les premiers exports sont disponibles dans la version 0.5.2.

Désolé, mais je bute toujours sur compensation.
Si je prends un exemple plus réaliste,
J'ai besoin de faire un versement pour acheter des aliments au début du mois. +3K
Je fais mes collectes, avec des volumes record, j'achete un peu d'aliments a credit. +120k - 100k
A la fin du mois, droit d'achat = mon compte le lait (20k) + versements du debut du mois (3K).
=> 23k
Or si on ne compte pas les versements, je n'ai que 20k non ?

**Comment by 926** [comment]
Bonjour Mari, bien reçu,
Désolé j'ai revu les montants après dans l'exemple, d'où la confusion entre 3k et 1k... 
Mais on est d'accord que la compense doit déduire les versements clients.

Compense = solde fournisseur du mois - solde client du mois
Solde fournisseur = Credit - Debit
Solde client = Credit - Debit

La version 0.5.2 inclut l'export compensé, via ce bouton :

![image](https://user-images.githubusercontent.com/14161798/86252883-0fb13300-bbb4-11ea-9d20-bdb5ad24c067.png)
